name: eyeagent
description: "An agent to make life easier."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.2.6 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  english_words: ^4.0.0
  provider: ^6.0.0
  camera: ^0.10.5+9
  path_provider: ^2.1.2
  path: ^1.8.3
  camera_windows: ^0.2.1+9
  supabase_flutter: ^2.3.2
  google_sign_in: ^6.2.1
  timeago: ^3.6.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
